name: Trigger deployment
on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    name: Trigger deployment
    runs-on: ubuntu-latest
    steps:
      - name: Trigger webhook
        run: | 
        curl --request POST \
          --url 'https:///sjp-covid-20-sun816.vercel.app/api/cron' \
          --header 'Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}'
