name: Trigger deployment
on:
  workflow_dispatch:

jobs:
  build:
    name: Trigger deployment
    runs-on: ubuntu-latest
    steps:
      - name: Trigger webhook
        run: curl -X POST ${{ vercel-develop-webhook.VERCEL_TOKEN }}
