name: Trigger deployment
on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build:
    name: Trigger deployment
    runs-on: ubuntu-latest
    steps:
      - name: Trigger webhook
        run: curl https://api.vercel.com/v1/integrations/deploy/QmdCd5vS9gFpTxLUoD8LcRoJ1e8MiQqkurLHuyN55WNKVy/GRJ29SyY8W
